# Generated by Django 4.0.4 on 2022-05-30 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_seller', '0002_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='pic',
            field=models.FileField(default='product.jpg', upload_to='products'),
        ),
    ]
