# Generated by Django 4.0.4 on 2022-06-02 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_buyer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='pic',
            field=models.FileField(default='anonymous.jpg', upload_to='buyer_images'),
        ),
    ]
